"""add ended_at to tenant_plans

Revision ID: 7c9b9d705636
Revises: 480924c77dd2
Create Date: 2026-05-03 11:50:40.890533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9b9d705636'
down_revision: Union[str, Sequence[str], None] = '480924c77dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'webhooks', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhooks', type_='foreignkey')
    op.drop_column('tenants', 'ended_at')
    # ### end Alembic commands ###
